-- Shader


VERTEX_ATTRIB_POSITION = 0;
VERTEX_ATTRIB_NORMAL = 1;
VERTEX_ATTRIB_TEXCOORD0 = 2;
VERTEX_ATTRIB_TEXCOORD1 = 3;
VERTEX_ATTRIB_BONE_ID = 4;
VERTEX_ATTRIB_BONE_WEIGHT = 5;
VERTEX_ATTRIB_COLOR = 6;
VERTEX_ATTRIB_NONE = 7;