-- OpenGL Constants

GL = {};

-- Primitive data types
GL.UNSIGNED_BYTE = 0;
GL.BYTE = 1;
GL.UNSIGNED_SHORT = 2;
GL.SHORT = 3;
GL.UNSIGNED_INT = 4;
GL.INT = 5;
GL.FLOAT = 6;


-- Drawing Modes
GL.LINES = 0;
GL.LINE_STRIP = 1;
GL.TRIANGLES = 2;
GL.TRIANGLE_STRIP = 3;

-- Blending
GL.ZERO = 0;
GL.ONE = 1;
GL.SRC_COLOR = 2;
GL.ONE_MINUS_SRC_COLOR = 3;
GL.DST_COLOR = 4;
GL.ONE_MINUS_DST_COLOR = 5;
GL.SRC_ALPHA = 6;
GL.ONE_MINUS_SRC_ALPHA = 7;
GL.DST_ALPHA = 8;
GL.ONE_MINUS_DST_ALPHA = 9;
GL.CONSTANT_COLOR = 10;
GL.ONE_MINUS_CONSTANT_COLOR = 11;
GL.CONSTANT_ALPHA = 12;
GL.ONE_MINUS_CONSTANT_ALPHA = 13;
GL.SRC_ALPHA_SATURATE = 14;
GL.SRC1_COLOR = 15;
GL.ONE_MINUS_SRC1_COLOR = 16;
GL.SRC1_ALPHA = 17;
GL.ONE_MINUS_SRC1_ALPHA = 18;

-- Colors
GL.RGBA = 0;


-- Depth Testing
GL.NEVER = 0;
GL.LESS = 1;
GL.EQUAL = 2;
GL.LEQUAL = 3;
GL.GREATER = 4;
GL.NOTEQUAL = 5;
GL.GEQUAL = 6;
GL.ALWAYS = 7;


-- Textures and Framebuffers


-- VAO and VBO


-- Shaders

